name: Build

on: # trigger
 # push: # whenever code is pushed to github the workflow automatically runs
  workflow_call: #whenever this workflow needs to be called from another worglow
 # workflow_dispatch: # whenever you want the workflow to be called manually
  #schedule: # whenever you want the workflow to be called at specfic point

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the code
      run: echo "Code build using docker"
