# name of the workflow
name: Code

# when the workflow should run
on:
  push:
# jobs in the workflow
jobs:
  code-checkout:
    runs-on: ubuntu-latest
    #steps in the workflow
    steps:
      - name: clone the code
        uses: actions/checkout@v7

      - name: print the message
        run: echo "echo code cloned"
        
